/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktop_app;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author 
 */
public class Desktop_Application extends javax.swing.JFrame {

    public String w;
   // public String v;

    /**
     * Creates new form Desktop_Application
     */
    public Desktop_Application() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        jMenu3.setText("Choose File");

        jMenuItem5.setText(".pdf");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText(".jpg");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Choose Drive");

        jMenuItem1.setText("Local Disk (C:)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Local Disk (D:)");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Local Disk (E:)");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Local Disk (F:)");
        jMenuItem4.setToolTipText("F");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:   
          try {
            FileReader fr = new FileReader("ami.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;
            //boolean isFound = false;
             jTextArea1.setText("List of files :\n");
            while ((line = br.readLine()) != null) {
                System.out.println("line=" + line);
              
               jTextArea1.append("\n"+line);

            }

        } catch (Exception ex) {
            System.out.println("error" + ex);

        }
//
//        try {
//            FileReader fr = new FileReader("ami.txt");
//            BufferedReader br = new BufferedReader(fr);
////            while () {
////                System.out.println("Printing...");
////                String line = br.readLine();
////                //jTextField1.setText(line);
////                if (line != null) {
////                    //break;
////                    
////                }
////                
////
////              // br.close();  
////            }
//            System.out.println("Hiiiiiiiiiiiiiiii");
//            String line;
//            while ((line = br.readLine()) != null) {
//                jTextArea1.setText(line);
//                System.out.println("lol" + line);
//
//            }
//
//        } catch (Exception ex) {
//            System.out.println("Error");
//        }
        //String ss = jTextField1.getText();
        //System.out.println(ss);
        // All Folder in a drive
//        File f = new File("D:\\");
//        File[] folder = f.listFiles();
//        for (int i = 0; i < folder.length; i++) {
//            File Folder = folder[i];
//            System.out.println(Folder);
//
//        }
//        for (int i = 0; i < folder.length; i++) {
//            File Folder = folder[i];
//            //System.out.println(Folder);
//             String name = Folder.getName();
//                if (name.equals(ss)) {
//                    System.out.println(name);
//                }
//        }
        // How manr drives in this pc
//        File[] drives = File.listRoots();
//        if (drives != null && drives.length > 0) {
//            for (File aDrive : drives) {
//                System.out.println(aDrive);
//            }
//        }
//        File f = new File("F:\\");
//        File[] folder = f.listFiles();
//        for (int i = 0; i < folder.length; i++) {
//            File Folder = folder[i];
//            String name = Folder.getName();
//            if (name.endsWith(".pdf")) {
//                jTextField1.setText(name);
//            }
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFileChooser ch = new JFileChooser("C:");
        ch.showOpenDialog(null);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JFileChooser ch = new JFileChooser("E:");
        w = jMenuItem3.getText();
        ch.showOpenDialog(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser ch = new JFileChooser("D:");
        ch.showOpenDialog(null);
        //Object[] a = jMenu1.getSelectedObjects();
        w = jMenuItem2.getText();
        System.out.println(w);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JFileChooser ch = new JFileChooser("F:");
        // Object[] a = jMenu1.getSelectedObjects();
        w = jMenuItem4.getText();
        System.out.println(w);
        // ch.getApproveButtonToolTipText();
        //String a=ch.equals("Local Disk (F:)");
        //String a=ch.getApproveButtonToolTipText();
        //System.out.println("pop"+a);
        //ch.showOpenDialog(null);     


    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        //PrintWriter pw = null;
        System.out.println("Hello");
        // TODO add your handling code here:
        // pw = new PrintWriter("ami.txt");

        if (w.equals("Local Disk (D:)")) {
            System.out.println("Hello D");
            File ff = new File("D:\\");
            File[] folder = ff.listFiles();
            for (int i = 0; i < folder.length; i++) {
                File Folder = folder[i];
                String name = Folder.getName();
                if (name.endsWith(".pdf")) {
                    // pw.println(name);
                    //jTextField1.setText(name);
                    System.out.println(name);
                    //System.out.println("Hi");
                }
                
            }

        } //System.out.println("Print F");
        else if (w.equals("Local Disk (F:)")) {
            System.out.println("Hello F");
            File f = new File("F:\\");
            File[] folder = f.listFiles();
            for (int i = 0; i < folder.length; i++) {
                File Folder = folder[i];
                String name = Folder.getName();
                if (name.endsWith(".pdf")) {
                    // pw.println(name);
                    //jTextField1.setText(name);
                    System.out.println(name);
                    //System.out.println("Hi");
                }
            }
        } else if (w.equals("Local Disk (E:)")) {
            System.out.println("Hello E");
            File f = new File("E:\\");
            File[] folder = f.listFiles();
            for (int i = 0; i < folder.length; i++) {
                File Folder = folder[i];
                String name = Folder.getName();
                if (name.endsWith(".pdf")) {
                    // pw.println(name);
                    //jTextField1.setText(name);
                    System.out.println(name);
                    System.out.println("Hi");
                }

            }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        try {
            PrintWriter pw = new PrintWriter("ami.txt");
            if (w.equals("Local Disk (E:)")) {
                System.out.println("Hello E");
                File f = new File("E:\\");
                File[] folder = f.listFiles();
                for (int i = 0; i < folder.length; i++) {
                    File Folder = folder[i];
                    String name = Folder.getName();
                    if (name.endsWith(".jpg")) {
                        pw.println(name);
                        //jTextField1.setText(name);
                        System.out.println(name);
                        System.out.println("Hi");
                    }

                }
                pw.flush();
                pw.close();
            }
        } catch (Exception ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop_Application.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop_Application.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop_Application.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop_Application.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop_Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
